---
jobs:
  - name: run-local-test
    plan:
      - get: spring-boot-music
        trigger: true
      - get: pipeline-tasks
      - task: test
        file: pipeline-tasks/beanstalk/tasks/test.yml
        input_mapping:
          ci-tasks: pipeline-tasks
        params:
          ENV: "test"

  - name: build
    plan:
      - get: spring-boot-music
        passed: [run-local-test]
      - get: pipeline-tasks

  - name: deploy-to-beanstalk
    plan:
      - get: spring-boot-music
        passed: [build]
      - get: pipeline-tasks

  - name: run-acceptance
    plan:
      - get: spring-boot-music
        passed: [deploy-to-beanstalk]
      - get: pipeline-tasks

# All external Things which has to be in place for runing the jobs
resources:
  - name: spring-boot-music
    type: git
    source:
      uri: https://github.com/idev4u/spring-music.git
      branch: master
  - name: pipeline-tasks
    type: git
    source:
      uri: https://github.com/idev4u/spring-music-ci.git
      branch: main
